- .github/workflows/ci.yaml
- .github/workflows/pr-for-updates.yaml
- .golangci.yml
- README.md
- go.mod
Signed-off-by: Sergey Semenov <sergey.semenov@xored.com>
> Add github CI

- pkg/sriov/pcifunction/function.go
- pkg/sriov/pcifunction/physical_function.go
1. Rework `getVirtualFunctions`
2. Rework driver binding
> Rework pcifunctions

- go.mod
- go.sum
- pkg/networkservice/common/mechanisms/vfio/client.go
- pkg/networkservice/common/mechanisms/vfio/server.go
- pkg/networkservice/common/resourcepool/server.go
- pkg/networkservice/common/resourcepool/server_test.go
- pkg/sriov/config/config.go
Signed-off-by: Artem Glazychev <artem.glazychev@xored.com>
> Update to new logger usage

- go.mod
- go.sum
- pkg/networkservice/common/mechanisms/vfio/client.go
- pkg/networkservice/common/mechanisms/vfio/server.go
- pkg/networkservice/common/resourcepool/server.go
- pkg/networkservice/common/resourcepool/server_test.go
- pkg/sriov/config/config.go
Signed-off-by: Artem Glazychev <artem.glazychev@xored.com>
> Update to latest sdk version

- go.mod
- go.sum
- pkg/networkservice/chains/xconnectns/server.go
Signed-off-by: Anatoly Loskutnikov <anatoly.loskutnikov@gmail.com>
> Update to latest sdk and sdk-kernel versions

- go.mod
- go.sum
- pkg/networkservice/chains/xconnectns/server.go
Signed-off-by: Anatoly Loskutnikov <anatoly.loskutnikov@gmail.com>
> Update to latest sdk-kernel

- pkg/networkservice/chains/xconnectns/server.go
Signed-off-by: Artem Belov <artem.belov@xored.com>
> Fix heal update

- .github/workflows/ci.yaml
- .github/workflows/release.yaml
- .github/workflows/update-dependent-repositories-gomod.yaml
Signed-off-by: denis-tingajkin <denis.tingajkin@xored.com>
> feat: Add release actions

- go.mod
- go.sum
Signed-off-by: denis-tingajkin <denis.tingajkin@xored.com>
> Manually update to latest go.mod and go.sum

- .github/workflows/release.yaml
- .github/workflows/update-dependent-repositories-gomod.yaml
Signed-off-by: denis-tingajkin <denis.tingajkin@xored.com>
> Subscribe cmd-nsc-init on updates from sdk-sriov

- pkg/networkservice/common/mechanisms/vfio/server_test.go
#195
We cannot call `require(...)` inside other `require(...)`, because inner one call `t.FailNow()` in case of an error.
Signed-off-by: Artem Glazychev <artem.glazychev@xored.com>
> Fix data races

- .github/workflows/update-dependent-repositories-gomod.yaml
#196 
Signed-off-by: Artem Glazychev <artem.glazychev@xored.com>
> Update to right sdk version using go get

- go.mod
- go.sum
Closes https://github.com/networkservicemesh/sdk-sriov/pull/221.
> Manually update to the latest sdk-kernel version

- .github/workflows/release.yaml
- .github/workflows/update-dependent-repositories-gomod.yaml
add `sdk-ovs `repo as ci and release dependent for `sdk-sriov`
> add sdk-ovs as dependent repo

- pkg/networkservice/common/token/server.go
nil access caused panic in sriov ci test.
Thanks @Bolodya1997 for the logs.
> fix for sriov ci test failure

- .github/workflows/release.yaml
- .github/workflows/update-dependent-repositories-gomod.yaml
> add cmd-nse-icmp-responder as dependent repo

- pkg/networkservice/chains/xconnectns/server.go
- pkg/networkservice/common/mechanisms/noop/client.go
Enables NOOP mechanism for local cases.
> [qfix] Enable NOOP mechanism for local cases

- pkg/networkservice/common/resourcepool/server.go
- pkg/networkservice/common/token/client.go
- pkg/networkservice/common/token/common.go
- pkg/networkservice/common/token/server.go
> do not invoke next.Close when connection not established and use local cache for isEstablished flag

- .github/workflows/release.yaml
- .github/workflows/update-dependent-repositories-gomod.yaml
> [sdk-sriov] add cmd-nse-vlan-vpp as dependent repo

- pkg/networkservice/chains/forwarder/server.go
Signed-off-by: denis-tingaikin <denis.tingajkin@xored.com>
> qfix: Update to latest sdk manually

- .github/workflows/release.yaml
- .github/workflows/update-dependent-repositories-gomod.yaml
Signed-off-by: denis-tingaikin <denis.tingajkin@xored.com>
> qfix: Subscribe cmd-forwarder-vpp on updates from sdk-sriov

- pkg/networkservice/common/mechanisms/vfio/server_test.go
Signed-off-by: Oleg Solodkov <oleg.solodkov@xored.com>
> Skipped unstable tests

- pkg/sriov/pci/pool.go
This provides a new NewPCIPool API to skip kernel driver bind check as it always checks kernel interface present on the pci device. It's no more valid for VLAN trunking scenario as interface is moved into NSE container when first NS client shows up and won't be present for subsequent NS clients.
Will update cmd-forwarder-ovs to consume NewPCIPool API once this PR is merged.
> skip kernel driver bind check

- pkg/networkservice/chains/forwarder/server.go
Signed-off-by: Denis Tingaikin <denis.tingajkin@xored.com>
> qfix: Add registry sendfd client

- go.mod
- go.sum
- pkg/networkservice/chains/forwarder/server.go
Closes: https://github.com/networkservicemesh/sdk-sriov/pull/408
> Update registry client

- .github/workflows/automerge.yaml
- .github/workflows/ci.yaml
- .github/workflows/codeql-analysis.yml
- .github/workflows/pr-for-updates.yaml
- .github/workflows/release.yaml
- .github/workflows/update-dependent-repositories-gomod.yaml
- pkg/networkservice/common/mechanisms/vfio/client_test.go
Signed-off-by: Nikita Skrynnik <nikita.skrynnik@xored.com>
https://github.com/networkservicemesh/.github/issues/4
> Reusable workflows

- pkg/networkservice/chains/forwarder/server.go
Signed-off-by: anastasia.malysheva <anastasia.malysheva@xored.com>
> Enable authorize monitor connection server

- pkg/networkservice/chains/forwarder/server.go
Signed-off-by: Nikita Skrynnik <nikita.skrynnik@xored.com>
> Fix linter issues after update golangci-lint version

- pkg/networkservice/common/token/multitoken/client.go
Issue: https://github.com/networkservicemesh/sdk-sriov/issues/489
> [qfix] Add error checking to tokenClient
